# Preload all 4 wallpapers
preload = ~/.config/hypr/wallpapers/circles.png
preload = ~/.config/hypr/wallpapers/summer.png
preload = ~/.config/hypr/wallpapers/summer2.png
preload = ~/.config/hypr/wallpapers/nice_view.png

# Set initial wallpapers
wallpaper = DP-3,~/.config/hypr/wallpapers/circles.png
wallpaper = HDMI-A-1,~/.config/hypr/wallpapers/summer2.png

splash = false
ipc = on
